name: 27_08_FridayExcerciseCIandTDD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"
      - name: Setup on Latest MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: "latest"
          mysql database: "startcode"
          mysql user: "dev"
          mysql password: "ax2"

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify